### ISSUE TITLE
Can't build after cloning repo

### ISSUE THREAD

**Issue by Cpt-Falcon** [john-h-k/MathSharp#128]
Hello,

I cloned the repo and tried both running the build.cmd script and going through visual studio build solution. Both have the following error:

I'm not sure if i'm doing something wrong, but I see this error:

1>C:\Users\aruss\Downloads\MathSharp-master\sources\MathSharp\Vector\Shared\BitComparisons.cs(8,33,8,39): error CS0101: The namespace 'MathSharp' already contains a definition for 'Vector'

Thanks

**Comment by Netkicks** [comment]
Same...any luck with this?

**Comment by Svengali** [comment]
So, I synced to 1f0f80390d0ae5280dac60ae10cdae54a0f68bcb (Update README.md) and I can build from there.  

I havent tracked down what changes the later checkins affect, but at least its buildable from there.

**Comment by john-h-k** [comment]
Fixed
