### ISSUE TITLE
Feasiblity of remove strong-name signing?

### ISSUE THREAD

**Issue by Perksey** [john-h-k/MathSharp#8]
Strong-name signing isn't really used anymore and has caused a bunch of issues in OpenTK, thus we no longer recommend it. Plus, NuGet.org has it's own signature validation system so snk isn't really needed.

Consider removal?

**Comment by john-h-k** [comment]
This seems fine, I can get round to it at some point but it is a simple PR if anyone else is up to it

**Comment by varon** [comment]
Definitely remove it. Apparently causes issues with GLControl too.

**Comment by john-h-k** [comment]
#38
